PACKAGE_NAME="alx-wol"
PACKAGE_VERSION="3.2"

BUILT_MODULE_NAME[0]="alx"
BUILT_MODULE_LOCATION[0]="alx/"
DEST_MODULE_NAME[0]="alx"
# DEST_MODULE_LOCATION[0] has to be the path of the original module
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/ethernet/atheros/alx"

source $source_tree/$PACKAGE_NAME-$PACKAGE_VERSION/dkms_base.conf
