PACKAGE_NAME="pata_acpi_test"
PACKAGE_VERSION="3.2"

BUILT_MODULE_NAME[0]="pata_acpi"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_NAME[0]="pata_acpi"
# DEST_MODULE_LOCATION[0] has to be the path of the original module
DEST_MODULE_LOCATION[0]="/kernel/drivers/ata"

source $source_tree/$PACKAGE_NAME-$PACKAGE_VERSION/dkms_base.conf
